feat(file-picker): Create the option to define a limit for the number of files picked by user #17
capawesome-team/capacitor-plugins pull request #108
Opened 2023-12-29 10:51 UTC by stephan-fischer

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).
- [x] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2023-12-29 15:00 UTC, danbunkr commented
@robingenz - This would be a huge win for our application if we could get this merged even if its just for IOS

2023-12-29 16:04 UTC, robingenz requested changes
Please also update the `definitions.ts` file and run `npm run docgen`:

```diff
export interface PickMediaOptions {
+  /**
+   * The maximum number of files that the user can select.
+   *
+   * This option is ignored if `multiple` is set to `false`.
+   *
+   * Only available on iOS.
+   *
+   * @example 4
+   */
+  limit?: number;
  ...
```

2023-12-29 16:04 UTC, robingenz commented on .changeset/heavy-dancers-impress.md
> +feat(file-picker): Create the option to define a limit for the number of files picked by user - only on ios
```suggestion
feat(ios): add `limit` option
```

2023-12-29 16:04 UTC, robingenz commented on .changeset/heavy-dancers-impress.md
> +'@capawesome/capacitor-file-picker': patch
```suggestion
'@capawesome/capacitor-file-picker': minor
```

2023-12-29 19:16 UTC, stephan-fischer reviewed
thank you!

2023-12-29 19:23 UTC, stephan-fischer commented
@robingenz do i have to accept somewhere the changes? Sorry first time here creating a pull request and accepting changes

2023-12-29 21:55 UTC, robingenz commented
@stephan-fischer No problem, that will be squashed anyway.

2023-12-29 21:55 UTC, robingenz approved these changes

2023-12-29 22:00 UTC, robingenz commented
@stephan-fischer Please run `npm run fmt`.

2023-12-29 22:01 UTC, robingenz requested changes
Please run `npm run fmt`.

2023-12-30 08:20 UTC, stephan-fischer reviewed
Reviewed

2023-12-30 09:33 UTC, robingenz approved these changes
Thank you!

2023-12-30 09:34 UTC, merged