bug(file-picker): pickFiles on Safari web does not bring up file pick…
capawesome-team/capacitor-plugins pull request #111
Opened 2023-12-29 18:05 UTC by stephan-fischer

…er on first call #14

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).
- [x] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2023-12-29 21:50 UTC, robingenz requested changes

2023-12-29 21:50 UTC, robingenz commented on .changeset/funny-taxis-tie.md
> +bug(file-picker): pickFiles on Safari web does not bring up file picker on first call #14
```suggestion
fix(web): `pickFiles (...)` doesn't work first time on Safari
```

2023-12-29 21:50 UTC, robingenz commented on .changeset/funny-taxis-tie.md
> +'@capawesome/capacitor-file-picker': minor
```suggestion
'@capawesome/capacitor-file-picker': patch
```

2023-12-29 21:50 UTC, robingenz commented on packages/file-picker/src/index.ts
> +    web:  () => new web.FilePickerWeb()
```suggestion
  web:  () => new web.FilePickerWeb()
```

2023-12-29 21:50 UTC, robingenz commented on packages/file-picker/src/index.ts
> +import * as web from './web';
```suggestion
// See https://github.com/capawesome-team/capacitor-plugins/issues/14
import * as web from './web';
```

2023-12-30 07:27 UTC, stephan-fischer reviewed
thank you 😊

2023-12-30 08:25 UTC, stephan-fischer reviewed
Reviewed

2023-12-30 09:34 UTC, stephan-fischer commented
@robingenz could you test this code, or is it possible to test the code previously via github package etc? I think we are only one step closer - i dont know if it works on compiled ts code.

2023-12-30 09:37 UTC, robingenz commented
@stephan-fischer Sure, i just published a dev version:

```
npm i @capawesome/capacitor-file-picker@5.1.1-dev.fbc4f0a.1703929046
```

2023-12-30 09:41 UTC, robingenz commented
Before: https://capacitor-plugin-demo-8imy2i1j7-robingenz.vercel.app/
After: https://capacitor-plugin-demo-rcpboxsdr-robingenz.vercel.app/

2023-12-30 09:41 UTC, stephan-fischer commented
> @stephan-fischer Sure, i just published a dev version:
> 
> ```
> npm i @capawesome/capacitor-file-picker@5.1.1-dev.fbc4f0a.1703929046
> ```

Thank you, it works 🤩

2023-12-30 09:48 UTC, robingenz approved these changes

2023-12-30 09:49 UTC, merged