#33 PackageManager.getPackageInfo(packageName, 0) is deprecated as of…
capawesome-team/capacitor-plugins pull request #134
Opened 2024-02-03 19:48 UTC by co-dax

… API 33: Android 13.0 (Tiramisu).

https://github.com/capawesome-team/capacitor-plugins/issues/131

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2024-02-03 20:34 UTC, robingenz requested changes
Thank you for your contribution.

2024-02-03 20:34 UTC, robingenz commented on packages/app-update/android/src/main/java/io/capawesome/capacitorjs/plugins/appupdate/AppUpdatePlugin.java
> +        // PackageManager.getPackageInfo(packageName, 0) is deprecated as of API 33: Android 13.0 (Tiramisu).
Please remove the comment. The code should be enough.

2024-02-03 20:34 UTC, robingenz commented on packages/app-update/android/src/main/java/io/capawesome/capacitorjs/plugins/appupdate/AppUpdatePlugin.java
> +
Please remove the empty line.

2024-02-04 13:11 UTC, co-dax commented
Done.

On Sat, Feb 3, 2024 at 9:34 PM Robin Genz ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thank you for your contribution.
> ------------------------------
>
> In
> packages/app-update/android/src/main/java/io/capawesome/capacitorjs/plugins/appupdate/AppUpdatePlugin.java
> <https://github.com/capawesome-team/capacitor-plugins/pull/134#discussion_r1477123569>
> :
>
> > @@ -227,7 +229,13 @@ private boolean isGooglePlayServicesAvailable() {
>
>      private PackageInfo getPackageInfo() throws PackageManager.NameNotFoundException {
>          String packageName = this.getContext().getPackageName();
> -        return this.getContext().getPackageManager().getPackageInfo(packageName, 0);
> +
> +        // PackageManager.getPackageInfo(packageName, 0) is deprecated as of API 33: Android 13.0 (Tiramisu).
>
> Please remove the comment. The code should be enough.
> ------------------------------
>
> In
> packages/app-update/android/src/main/java/io/capawesome/capacitorjs/plugins/appupdate/AppUpdatePlugin.java
> <https://github.com/capawesome-team/capacitor-plugins/pull/134#discussion_r1477123591>
> :
>
> > @@ -227,7 +229,13 @@ private boolean isGooglePlayServicesAvailable() {
>
>      private PackageInfo getPackageInfo() throws PackageManager.NameNotFoundException {
>          String packageName = this.getContext().getPackageName();
> -        return this.getContext().getPackageManager().getPackageInfo(packageName, 0);
> +
>
> Please remove the empty line.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/capawesome-team/capacitor-plugins/pull/134#pullrequestreview-1861121089>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABZ6CNHAZYY3UWSYW6FECC3YR2NO5AVCNFSM6AAAAABCYIBPTSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNRRGEZDCMBYHE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-05 07:48 UTC, closed without merging