Feat/issue 343 implementation
capawesome-team/capacitor-plugins pull request #373
Opened 2024-12-26 15:32 UTC by ebarooni

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).
- [x] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

2024-12-26 20:33 UTC, ebarooni commented
@robingenz All platforms are tested ✅

2024-12-27 08:07 UTC, robingenz requested changes
Looks great! Just a few comments.

2024-12-27 08:07 UTC, robingenz commented on packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/Screenshot.java
> +    public void take(Context context, @NonNull NonEmptyCallback<Result> callback) {
```suggestion
    private final ScreenshotPlugin plugin;

    public Screenshot(@NonNull ScreenshotPlugin plugin) {
        this.plugin= plugin;
    }

    public void take(@NonNull NonEmptyCallback<Result> callback) {
```

Please pass the plugin instance and remove the context param, see https://github.com/capawesome-team/capacitor-plugins/blob/b5088c73cef1e2be5d915d1ed7a0649865a3d3ca/packages/live-update/android/src/main/java/io/capawesome/capacitorjs/plugins/liveupdate/LiveUpdate.java#L92

2024-12-27 08:07 UTC, robingenz commented on packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/ScreenshotPlugin.java
> +        }
```suggestion
        this.implementation = new Screenshot(this);
```

2024-12-27 08:07 UTC, robingenz commented on packages/screenshot/android/src/main/java/io/capawesome/capacitorjs/plugins/screenshot/ScreenshotPlugin.java
> +            implementation.take(getContext(), callback);
```suggestion
            implementation.take(callback);
```

2024-12-27 08:07 UTC, robingenz commented on packages/screenshot/ios/Plugin/Screenshot.swift
> +    }
Please do the same here and pass the plugin instance, see https://github.com/capawesome-team/capacitor-plugins/blob/b5088c73cef1e2be5d915d1ed7a0649865a3d3ca/packages/live-update/ios/Plugin/LiveUpdate.swift#L24

2024-12-27 08:07 UTC, robingenz commented on packages/screenshot/ios/Plugin/Classes/Enums/CustomError.swift
> +    case webviewUnAvailable
```suggestion
    case webviewUnavailable
```

2025-01-02 08:06 UTC, robingenz approved these changes
@ebarooni LGTM 🎉

2025-01-02 08:07 UTC, merged