feat(cloudinary): add `secure_url` property
capawesome-team/capacitor-plugins pull request #70
Opened 2023-08-29 16:02 UTC by eranshmil

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

2023-08-29 16:46 UTC, robingenz requested changes
Hi @eranshmil,
thank you for your contribution.

According to the Cloudinary docs, there seems to be both: `url` and `secure_url` (see [here](https://cloudinary.com/documentation/upload_images#upload_response))

Feel free to add `secure_url`, but `url` should stay. Please also update the `definitions.ts` file and run `npm run docgen`.

2023-08-29 17:35 UTC, EranClientside commented
> Hi @eranshmil, thank you for your contribution.
> 
> According to the Cloudinary docs, there seems to be both: `url` and `secure_url` (see [here](https://cloudinary.com/documentation/upload_images#upload_response))
> 
> Feel free to add `secure_url`, but `url` should stay. Please also update the `definitions.ts` file and run `npm run docgen`.

Yeah, I saw that in the docs, but did it that way just like it's implemented in the [web implementation](https://github.com/capawesome-team/capacitor-plugins/blob/main/packages/cloudinary/src/utils.ts#L49).
Should I align all the properties in the web implementation?

2023-08-29 17:35 UTC, eranshmil commented
> Hi @eranshmil, thank you for your contribution.
> 
> According to the Cloudinary docs, there seems to be both: `url` and `secure_url` (see [here](https://cloudinary.com/documentation/upload_images#upload_response))
> 
> Feel free to add `secure_url`, but `url` should stay. Please also update the `definitions.ts` file and run `npm run docgen`.

Yeah, I saw that in the docs, but did it that way just like it's implemented in the [web implementation](https://github.com/capawesome-team/capacitor-plugins/blob/main/packages/cloudinary/src/utils.ts#L49).
Should I align all the properties in the web implementation?

2023-08-29 18:26 UTC, robingenz commented
Well spotted! Please add the new property `secure_url` on all platforms. I will replace `url: response.secure_url` with `url: response.url` on the web in a seperate PR.

2023-08-31 19:38 UTC, robingenz requested changes
Please make these changes and we can merge it. 👍

2023-08-31 19:38 UTC, robingenz commented on .changeset/mean-maps-shop.md
> +'@capawesome/capacitor-cloudinary': patch
```suggestion
'@capawesome/capacitor-cloudinary': minor
```

2023-08-31 19:38 UTC, robingenz commented on .changeset/mean-maps-shop.md
> +feat(cloudinary): add secure url property
```suggestion
feat(cloudinary): add `secure_url` property
```

2023-08-31 19:38 UTC, robingenz commented on packages/cloudinary/README.md
> +| **`secureUrl`**        | <code>string</code>                                   | The secure url of the uploaded resource.                                                 | 5.0.1 |
```suggestion
| **`secureUrl`**        | <code>string</code>                                   | The secure url of the uploaded resource.                                                 | 5.1.0 |
```

2023-08-31 19:38 UTC, robingenz commented on packages/cloudinary/docs/utils/README.md
> +| **`secureUrl`**        | <code>string</code>                                   | The secure url of the uploaded resource.                                                 | 5.0.1 |
```suggestion
| **`secureUrl`**        | <code>string</code>                                   | The secure url of the uploaded resource.                                                 | 5.1.0 |
```

2023-08-31 19:38 UTC, robingenz commented on packages/cloudinary/src/definitions.ts
> +   * @since 5.0.1
```suggestion
   * @since 5.1.0
```

2023-08-31 21:36 UTC, merged

2023-08-31 21:37 UTC, robingenz commented
@eranshmil Thank you for your contribution!